### PR TITLE
feat(useTimeout): handle large delays

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by jquense** [comment]
i don't currently need to...at least i don't think so...

**Comment by taion** [comment]
okay, sorry, now that i'm looking at this again... this is actually going to have a very slightly wrong timeout because we're not accounting for drift in firing the timeout

this probably makes no practical difference, but it wasn't a problem in our internal implementation because we were skipping the `setTimeout` abstraction entirely and just calculating from the intended expiration time

would it make sense here to calculate `Date.now() + ms`, and keep trying to schedule toward that time?

**Comment by jquense** [comment]
added accounting for drift, tho i did it super quickly so plz check my work

**Comment by taion** [comment]
@jquense tried to clean up the logic a bit; let me know what you think

**Comment by jquense** [comment]
LGTM!

**Pull request merged**
