### PR TITLE
feat: remove lodash

### LINKED ISSUE #34: Remove lodash dependency
Per https://npmjs.com/advisories/1523. It seems like it's only used for isEqual  in useMutationObserver

### PR DESCRIPTION
**Pull request by jquense**
closes #34 Hows this look @TrySound ?

### CODE REVIEW

**Comment by TrySound** [comment]
There is no esm support.
https://unpkg.com/browse/react-fast-compare@3.2.0/

dequal has it.
https://unpkg.com/browse/dequal@1.0.0/dist/

**Comment by jquense** [comment]
would that matter here? there is nothing to tree shake

**Comment by TrySound** [comment]
There is more to process for rollup users. For example I keep "include" list for all commonjs dependencies to speed up build and reduce memory usage.

**Comment by TrySound** [comment]
Also webpack 4 wraps every commonjs module with function which prevents its scope hoisting.

**Comment by Twipped** [comment]
You could also just do it the way React does it:

```js

function areHookInputsEqual (nextDeps, prevDeps) {
  const is = Object.is || ((x, y) => (x === y && (x !== 0 || 1 / x === 1 / y)) || (x !== x && y !== y)); // eslint-disable-line no-self-compare

  if (prevDeps === null) {
    return false;
  }

  for (let i = 0; i < prevDeps.length && i < nextDeps.length; i++) {
    if (!is(nextDeps[i], prevDeps[i])) return false;
  }
  return true;
}
```

See https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberHooks.new.js#L286

**Pull request merged**
