### PR TITLE
feat: add useSafeState

### PR DESCRIPTION
**Pull request by jquense**

### CODE REVIEW

**Comment by taion** [comment]
eh, seems like in most cases you wouldn't want to wrap `useState` explicitly.

can we make higher-order hooks a thing?

**Comment by jquense** [comment]
this is more flexible i think, i didn't really want to figure out the typing for overloading a default useState implementation

**Comment by taion** [comment]
wouldn't it just be `typeof useState`?

**Comment by jquense** [comment]
how would you disambiguate between `useSafeState(someDefaultValue)` and passing in the state object. I don't think i want to do higher order hooks, this seems nicer at still allows that if we want to wrap it in our app

**Comment by taion** [comment]
```js
const useSafeState = createUseWhatever(useState);
```

maybe?

**Comment by jquense** [comment]
that's more complex and more typing than this tho :P plus if you do it in render absentmindedly it's gonna fail badly. I don't know that i see the benefit over  the version here?

**Pull request merged**
